#!/bin/sh
base=`dirname "$(readlink -f "$0")"`
. "$base"/settings

set -e
version=`grep '^ceph' debian/changelog | sed 's/.*(\(.*\)).*/\1/' | head -n 1`
cat <<EOF >debian/changelog.dch
ceph (${version}~$SUFFIX) stable; urgency=low

  * Compiled for ARM

 -- "$NAME" <"$EMAIL">  `LANG=C date -R`

EOF
cat debian/changelog >> debian/changelog.dch
mv debian/changelog.dch debian/changelog
